import react, {useState, useEffect} from 'react'
import { GetServerSideProps } from 'next'
import Head from "next/head";
import Courses from "../components/Course"
import Lessons from '../components/Lessons/index'
import MyApp from './_app';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Dizipro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
      </Head>
      <main>
        <Courses/>
      </main>
    </div>
  );
}