import React, {useState, useEffect} from 'react'
import Head from "next/head";
import Courses from "../components/Course"
export default function Home() {



  return (
    <div>
      <Head>
        <title>Dizipro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Courses/>
      </main>
    </div>
  );
}